import type { Account, Category, Transaction, Budget, RecurringPayment, NotificationItem, AppSettings } from '../types/finance';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-food', name: 'Food', iconName: 'Utensils', color: '#10B981', type: 'EXPENSE' },
  { id: 'cat-shopping', name: 'Shopping', iconName: 'ShoppingBag', color: '#3B82F6', type: 'EXPENSE' },
  { id: 'cat-transport', name: 'Transport', iconName: 'Car', color: '#F59E0B', type: 'EXPENSE' },
  { id: 'cat-bills', name: 'Bills', iconName: 'FileText', color: '#EC4899', type: 'EXPENSE' },
  { id: 'cat-education', name: 'Education', iconName: 'GraduationCap', color: '#8B5CF6', type: 'EXPENSE' },
  { id: 'cat-entertainment', name: 'Entertainment', iconName: 'Film', color: '#06B6D4', type: 'EXPENSE' },
  { id: 'cat-other', name: 'Other', iconName: 'MoreHorizontal', color: '#6B7280', type: 'EXPENSE' },
  { id: 'cat-salary', name: 'Salary', iconName: 'Briefcase', color: '#10B981', type: 'INCOME' },
  { id: 'cat-freelance', name: 'Freelance', iconName: 'Laptop', color: '#34D399', type: 'INCOME' },
  { id: 'cat-transfer', name: 'Transfer', iconName: 'ArrowLeftRight', color: '#9CA3AF', type: 'EXPENSE' },
];

export const PRODUCTION_ACCOUNTS: Account[] = [];
export const PRODUCTION_TRANSACTIONS: Transaction[] = [];
export const PRODUCTION_BUDGETS: Budget[] = [];
export const PRODUCTION_RECURRING: RecurringPayment[] = [];
export const PRODUCTION_NOTIFICATIONS: NotificationItem[] = [];

export const DEMO_ACCOUNTS: Account[] = [
  {
    id: 'acc-sbi',
    name: 'SBI Bank',
    type: 'BANK',
    balance: 24500,
    openingBalance: 4500,
    institution: 'State Bank of India',
    color: '#059669',
    currency: '₹',
    isArchived: false,
    updatedAt: '2026-09-10T20:32:00Z',
  },
  {
    id: 'acc-hdfc',
    name: 'HDFC Bank',
    type: 'BANK',
    balance: 12300,
    openingBalance: 8730,
    institution: 'HDFC Bank',
    color: '#2563EB',
    currency: '₹',
    isArchived: false,
    updatedAt: '2026-09-10T19:15:00Z',
  },
  {
    id: 'acc-cash',
    name: 'Cash Wallet',
    type: 'CASH',
    balance: 2000,
    openingBalance: 4100,
    institution: 'Physical Cash',
    color: '#D97706',
    currency: '₹',
    isArchived: false,
    updatedAt: '2026-09-06T14:10:00Z',
  },
  {
    id: 'acc-card',
    name: 'Credit Card',
    type: 'CREDIT_CARD',
    balance: 4500,
    openingBalance: 0,
    creditLimit: 50000,
    institution: 'HDFC Bank Credit',
    color: '#F43F5E',
    currency: '₹',
    isArchived: false,
    updatedAt: '2026-09-09T18:45:00Z',
  },
];

export const DEMO_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    type: 'EXPENSE',
    amount: 350,
    accountId: 'acc-sbi',
    categoryId: 'cat-education',
    date: '2026-09-12',
    time: '14:30',
    merchant: 'College Canteen',
    note: 'Lunch at College Canteen',
    paymentMethod: 'UPI',
    locationName: 'MVR College of Engineering and Technology',
    locationAddress: 'Paritala, Kanchikacherla, Andhra Pradesh 521180',
    latitude: 16.5762,
    longitude: 80.4501,
    locationPlaceId: 'mvr_college_paritala',
    createdAt: '2026-09-12T14:30:00Z',
    updatedAt: '2026-09-12T14:30:00Z',
  },
  {
    id: 'tx-2',
    type: 'EXPENSE',
    amount: 1450,
    accountId: 'acc-hdfc',
    categoryId: 'cat-bills',
    date: '2026-09-11',
    time: '11:15',
    merchant: 'KIMS Hospital Pharmacy',
    note: 'Medical Checkup & Medicines',
    paymentMethod: 'Debit Card',
    locationName: 'KIMS Hospital',
    locationAddress: 'Vijayawada, Andhra Pradesh',
    latitude: 16.5123,
    longitude: 80.6284,
    locationPlaceId: 'kims_hospital_vja',
    createdAt: '2026-09-11T11:15:00Z',
    updatedAt: '2026-09-11T11:15:00Z',
  },
  {
    id: 'tx-3',
    type: 'INCOME',
    amount: 35000,
    accountId: 'acc-sbi',
    categoryId: 'cat-salary',
    date: '2026-09-01',
    time: '09:00',
    merchant: 'Employer Inc',
    note: 'Monthly Salary Credit',
    paymentMethod: 'Net Banking',
    locationName: 'SBI Branch Vijayawada',
    locationAddress: 'MG Road, Vijayawada, Andhra Pradesh',
    latitude: 16.5062,
    longitude: 80.648,
    locationPlaceId: 'sbi_vja_mgroad',
    createdAt: '2026-09-01T09:00:00Z',
    updatedAt: '2026-09-01T09:00:00Z',
  },
  {
    id: 'tx-4',
    type: 'TRANSFER',
    amount: 5000,
    accountId: 'acc-sbi',
    toAccountId: 'acc-hdfc',
    categoryId: 'cat-transfer',
    date: '2026-09-05',
    time: '11:45',
    note: 'Self Transfer to HDFC Bank',
    paymentMethod: 'UPI',
    createdAt: '2026-09-05T11:45:00Z',
    updatedAt: '2026-09-05T11:45:00Z',
  },
  {
    id: 'tx-5',
    type: 'EXPENSE',
    amount: 2200,
    accountId: 'acc-card',
    categoryId: 'cat-shopping',
    date: '2026-09-08',
    time: '16:40',
    merchant: 'Trends Shopping Mall',
    note: 'Clothing & Accessories',
    paymentMethod: 'Credit Card',
    // INTENTIONAL UNKNOWN LOCATION WITH COORDINATES
    latitude: 16.53,
    longitude: 80.61,
    createdAt: '2026-09-08T16:40:00Z',
    updatedAt: '2026-09-08T16:40:00Z',
  },
  {
    id: 'tx-6',
    type: 'EXPENSE',
    amount: 150,
    accountId: 'acc-cash',
    categoryId: 'cat-food',
    date: '2026-09-09',
    time: '19:20',
    merchant: 'Local Tea & Snack Stall',
    note: 'Evening Tea and Snacks',
    paymentMethod: 'Cash',
    // INTENTIONAL MANUAL LOCATION WITHOUT COORDINATES
    locationName: 'Hostel Paritala',
    locationAddress: 'Near College Gate, Paritala',
    createdAt: '2026-09-09T19:20:00Z',
    updatedAt: '2026-09-09T19:20:00Z',
  },
  {
    id: 'tx-7',
    type: 'EXPENSE',
    amount: 650,
    accountId: 'acc-hdfc',
    categoryId: 'cat-entertainment',
    date: '2026-09-06',
    time: '21:00',
    merchant: 'INOX Movies',
    note: 'Weekend Movie Ticket & Popcorn',
    paymentMethod: 'UPI',
    locationName: 'PVP Square Mall',
    locationAddress: 'MG Road, Vijayawada',
    latitude: 16.5041,
    longitude: 80.6432,
    createdAt: '2026-09-06T21:00:00Z',
    updatedAt: '2026-09-06T21:00:00Z',
  },
];

export const DEMO_BUDGETS: Budget[] = [
  { id: 'b-food', categoryId: 'cat-food', monthlyLimit: 5000 },
  { id: 'b-transport', categoryId: 'cat-transport', monthlyLimit: 2500 },
  { id: 'b-shopping', categoryId: 'cat-shopping', monthlyLimit: 4000 },
  { id: 'b-bills', categoryId: 'cat-bills', monthlyLimit: 6000 },
  { id: 'b-entertainment', categoryId: 'cat-entertainment', monthlyLimit: 2000 },
];

export const DEMO_RECURRING: RecurringPayment[] = [
  {
    id: 'rec-1',
    title: 'House Rent',
    amount: 8000,
    frequency: 'MONTHLY',
    nextDueDate: '2026-10-05',
    accountId: 'acc-sbi',
    categoryId: 'cat-bills',
    isPaused: false,
    reminderDaysBefore: 2,
    note: 'Owner Direct Transfer',
  },
  {
    id: 'rec-2',
    title: 'Netflix Subscription',
    amount: 649,
    frequency: 'MONTHLY',
    nextDueDate: '2026-09-18',
    accountId: 'acc-card',
    categoryId: 'cat-entertainment',
    isPaused: false,
    reminderDaysBefore: 1,
    note: 'Auto Debit Credit Card',
  },
  {
    id: 'rec-3',
    title: 'Mobile Recharge',
    amount: 299,
    frequency: 'MONTHLY',
    nextDueDate: '2026-09-22',
    accountId: 'acc-hdfc',
    categoryId: 'cat-bills',
    isPaused: false,
    reminderDaysBefore: 1,
    note: 'Jio 84 Days Plan',
  },
  {
    id: 'rec-4',
    title: 'Electricity Bill',
    amount: 1450,
    frequency: 'MONTHLY',
    nextDueDate: '2026-09-25',
    accountId: 'acc-sbi',
    categoryId: 'cat-bills',
    isPaused: false,
    reminderDaysBefore: 3,
    note: 'APSPDCL Bill',
  },
];

export const DEMO_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-demo-1',
    type: 'BUDGET_ALERT',
    title: 'Budget Alert: Food & Dining',
    message: 'You have used ₹3,850 of your ₹5,000 monthly food limit (77%).',
    date: '2026-09-12T10:00:00Z',
    isRead: false,
  },
  {
    id: 'notif-demo-2',
    type: 'RECURRING_REMINDER',
    title: 'Upcoming Bill: Netflix Subscription',
    message: '₹649 will be charged on 2026-09-18 for Netflix Subscription.',
    date: '2026-09-13T08:30:00Z',
    isRead: false,
  },
];

export const INITIAL_SETTINGS: AppSettings = {
  hideBalances: false,
  pinEnabled: false,
  hashedPin: '',
  currency: '₹',
  lastSyncedAt: new Date().toISOString(),
  demoModeLoaded: false,
};
